### PR TITLE
Improve function/variable names

### PR DESCRIPTION
**Pull request by roback**
- No more leading underscores in variable/function names (#10)
- Always use snake_case. (All tests are named with CamelCase though, but their examples are in camelCase. Different libraries/frameworks has different conventions: http://programmers.stackexchange.com/a/196463)

### CODE REVIEW

**Comment by walro** [comment]
> Always use snake_case. (All tests are named with CamelCase though, but their examples are in camelCase. Different libraries/frameworks has different conventions: http://programmers.stackexchange.com/a/196463)

http://programmers.stackexchange.com/a/149321 a bit more detailed, seems like camelCase is a bit more prominent.

**Comment by roback** [comment]
The reason I went with snake_case was that it only required one small change fe8e6fcf8d54d65e9f4a58f3af07592f16d3ffca :smile:

**Comment by walro** [comment]
It's OK, I used codeigniter for my master thesis (which seems to use snake_case) :D.

**Comment by roback** [comment]
> It's OK, I used codeigniter for my master thesis (which seems to use snake_case) :D

Phew :stuck_out_tongue_closed_eyes:

**Comment by walro** [comment]
LGTM

**Pull request merged**
