### PR TITLE
Convert Query#start_time and #end_time to UTC

### LINKED ISSUE #15: Convert query start and end time to UTC
The API uses UTC, so we can help the user by converting the supplied  `start_time` and `end_time` to UTC, so the user doesn't have to think about it.

References
- https://github.com/twingly/twingly-search-api-ruby/issues/43
- https://github.com/twingly/twingly-search-api-ruby/pull/46

### PR DESCRIPTION
**Pull request by roback**
Had to create a clone of the datetime object so we don't modify the original one. The tests checks that that the original one wasn't modified.

close #15

### CODE REVIEW

**Comment by dentarg** [comment]
> The tests checks that that the original one wasn't modified.

I thought this wasn't tested, but now I see it

``` php
$this->assertEquals($q->start_time->format('P'), '+01:00');
```

perhaps a more obvious test would be to compare the objects? it can even be it's own test case, like we do for the other clients (ruby, node), `it "should not modify ..."`

**Comment by roback** [comment]
> perhaps a more obvious test would be to compare the objects? it can even be it's own test case, like we do for the other clients (ruby, node)

Then the tests would pass even if we changed the original object, but I can move them into a separate testcase to make it more obvious.

**Comment by dentarg** [comment]
Hmm.., why would they? I'm not following along

**Comment by roback** [comment]
> Hmm.., why would they? I'm not following along

Because we would just compare the object with itself.

``` php
$time = new DateTime("... +01:00");
$start_time = $time;

$start_time->setTimezone(new \DateTimeZone('UTC'));

$time === $start_time // true
```

**Comment by dentarg** [comment]
Hmm, this is what I'm thinking of:

``` php
$time = new DateTime("... +01:00");
$q->start_time = $time;

$this->assertEquals($q->start_time, $time);
```

Like we do for example here https://github.com/twingly/twingly-search-api-ruby/blob/c525e3ef7a43a655209acf622360c595adb87fd2/spec/query_spec.rb#L105-L108

Maybe there something different about datetime objects in PHP vs Ruby that I'm not thinking of :)

**Comment by roback** [comment]
The test in ruby checks that `#start_time` is the same object, It doesn't check that the object has been modified. It's timezone could have been changed.

> Maybe there something different about datetime objects in PHP vs Ruby that I'm not thinking of :)

The difference is that I couldn't find a function in PHP that returned a new DateTime object in UTC, like ~~`Time#utc`~~ `Time#getutc` does in Ruby. PHP only has the `DateTime#setTimezone` function which modifies the original instead of returning a new instance. I just wanted to make sure that my usage of `clone` worked correctly :)

EDIT: its `Time#getutc` in Ruby

**Comment by dentarg** [comment]
I see, that test in the Ruby client isn't working properly I think...

``` ruby
[6] pry(main)> class Query ; def start_time=(time) ; @start_time = time.utc ; end ; def start_time ; @start_time ; end ; end
=> :start_time
[7] pry(main)> query = Query.new
=> #<Query:0x007fcb44e626e0>
[8] pry(main)> now = Time.now
=> 2016-02-25 11:59:10 +0100
[9] pry(main)> query.start_time = now
=> 2016-02-25 10:59:10 UTC
[10] pry(main)> now
=> 2016-02-25 10:59:10 UTC
[11] pry(main)> query.start_time == now
=> true
```

Also, `Time#utc` in Ruby doesn't return a new object, [it in a perfect world, it should be called `utc!`](https://pinboard.in/u:dentarg/b:041bda628d75)...

``` ruby
[27] pry(main)> now = Time.now
=> 2016-02-25 12:05:32 +0100
[28] pry(main)> now
=> 2016-02-25 12:05:32 +0100
[29] pry(main)> now.getutc
=> 2016-02-25 11:05:32 UTC
[30] pry(main)> now
=> 2016-02-25 12:05:32 +0100
[31] pry(main)> now.utc
=> 2016-02-25 11:05:32 UTC
[32] pry(main)> now
=> 2016-02-25 11:05:32 UTC
```

**Comment by dentarg** [comment]
Yes, you are right @roback, I tested my suggestion and it didn't work, the test did not fail when I removed the `clone` call in the implementation :)

LGTM, :shipit:

**Comment by roback** [comment]
> Also, Time#utc in Ruby doesn't return a new object, it in a perfect world, it should be called utc!...

Oops, my bad, it must have been `#getutc` I was thinking of :)

**Pull request merged**
